server:
   port: 8081
   
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: RECOMMENDED
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
#     properties:
#      hibernate:
#       dialect: org.hibernate.dialect.MySQL8Dialect
#  config:
#    import: configserver:http://localhost:8085
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-21933278.okta.com/oauth2/default
#      client:
#        registration:
#          my-internal-client:
#            provider: okta
#            authorization-grant-type: client_credentials
#            scope: internal
#            client-id: 0oa8fs7ix2tO4OUXy5d7
#            client-secret: 7PCFPViPulLgUwYu82wjr__Tl9MJkgGLGGo6NKht
#            
#        provider:
#          okta:
#            issuer-uri: https://dev-21933278.okta.com/oauth2/default
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#okta:
#  oauth2:
#    issuer: https://dev-21933278.okta.com/oauth2/default
#    audience: api://default